config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'home#index'
   get 'home' => 'home#index'
   get 'sync' => 'home#sync'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/configuration.rb
class Configuration < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :story

  def self.months
     Log.order(log_date: :desc).pluck(:log_date).map{ |d| d.strftime("%B") }.uniq
  end

  def self.total(from, to)
    Log.where('log_date >= ? AND log_date <= ?', from, to).sum(:time)
  end

  def self.today
    self.total(Date.today, Date.today)
  end

  def self.this_week
    self.total(Date.today.beginning_of_week, Date.today.end_of_week)
  end

  def self.this_month
    self.total(Date.today.beginning_of_month, Date.today.end_of_month)
  end

  def self.last_month
    self.total(Date.today.beginning_of_month - 1.month, Date.today.end_of_month - 1.month)
  end
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :logs

  def time_added?(value)
  	difference = (value - self.total_time)
  	difference.positive? && difference >= 900
  end
end

app/models/tracker_file.rb
class TrackerFile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @logs = Log.where('log_date > ? AND log_date < ?', DateTime.now.beginning_of_month, DateTime.now.end_of_month)
  end

  def sync
  	TimeLoad.new(DateTime.now, true).load_time
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container-wrap">
  <div id="fh5co-counter" class="fh5co-counters">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center animate-box">
        <p>Total time calculated from the exported files from tracker.</p>
        </div>
    </div>
    <div class="row animate-box">
      <div class="col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-md-3 text-center">
            <span class="fh5co-counter js-counter" data-from="0" data-to="<%= Log.last_month.summary %>" data-speed="500" data-refresh-interval="10"></span>
            <span class="fh5co-counter-label">Total Hours In Last Month</span>
          </div>
          <div class="col-md-3 text-center">
            <span class="fh5co-counter js-counter" data-from="0" data-to="<%= Log.this_month.summary %>" data-speed="500" data-refresh-interval="10"></span>
            <span class="fh5co-counter-label">Total Hours In This Month</span>
          </div>
          <div class="col-md-3 text-center">
            <span class="fh5co-counter js-counter" data-from="0" data-to="<%= Log.this_week.summary %>" data-speed="500" data-refresh-interval="10"></span>
            <span class="fh5co-counter-label">Total Hours In This Week</span>
          </div>
          <div class="col-md-3 text-center">
            <span class="fh5co-counter js-counter" data-from="0" data-to="<%= Log.today.summary %>" data-speed="500" data-refresh-interval="10"></span>
            <span class="fh5co-counter-label">Total Hours Today</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-wrap">
  <div id="fh5co-about">
      <div class="row animate-box">
        <div class="col-md-12 text-center heading-section">
          <% @logs.group_by{ |l| l.log_date.day }.each do |day, logs| %>
            <h3>October <%= day %></h3>
            <% logs.each do |log| %>
              <div class="row">
                <div class="col-md-2 text-center"><p>#<%= log.story.uid %></p></div>
                <div class="col-md-8 text-center"><p><%= link_to log.story.title, log.story.url %></p></div>
                <div class="col-md-2 text-center"><p><%= log.time.format %></p></div>
              </div>
            <% end %>
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center"><h5>TOTAL</h5></div>
                <div class="col-md-2 text-center"><h5><%= logs.map(&:time).sum.format %></h5></div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="fh5co-loader"></div>
  
    <div id="page">
      <nav class="fh5co-nav" role="navigation">
        <div class="container-wrap">
          <div class="top-menu">
            <div class="row">
              <div class="col-xs-2">
                <div id="fh5co-logo"><a href="index.html">WT Lite</a></div>
              </div>
              <div class="col-xs-10 text-right menu-1">
                <ul>
                  <li class="active"><a href="index.html">Home</a></li>
                  <li class="has-dropdown">
                    <a href="blog.html">Months</a>
                    <ul class="dropdown">
                      <% Log.months.each do |month| %>
                        <li><%= link_to month, home_path %></li>
                      <% end %>
                    </ul>
                  </li>
                  <li><%= link_to 'Sync', sync_path, remote: true %></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>